//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int commentId { get; set; }
        public Nullable<int> emailId { get; set; }
        public string poster { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string comment1 { get; set; }
    
        public virtual Email Email { get; set; }
    }
}
