//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public Email()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int EmailID { get; set; }
        public string Sender { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> RecievedTime { get; set; }
        public string Subject { get; set; }
        public string Reciever { get; set; }
        public string Assigned { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
